### ISSUE TITLE
onsenui CSS > 2.10.1 causing CSS compile error (clean-css)

### ISSUE THREAD

**Issue by ryanelian** [ryanelian/instapack#199]
```
ERROR during CSS build:
TypeError: value.split is not a function
    at track (F:\VS\instapack\node_modules\clean-css\lib\writer\source-maps.js:32:21)
    at store (F:\VS\instapack\node_modules\clean-css\lib\writer\source-maps.js:20:3)
    at value (F:\VS\instapack\node_modules\clean-css\lib\writer\helpers.js:117:7)
    at property (F:\VS\instapack\node_modules\clean-css\lib\writer\helpers.js:102:7)
    at body (F:\VS\instapack\node_modules\clean-css\lib\writer\helpers.js:62:5)
    at all (F:\VS\instapack\node_modules\clean-css\lib\writer\helpers.js:212:9)
    at serializeStylesAndSourceMap (F:\VS\instapack\node_modules\clean-css\lib\writer\source-maps.js:94:3)
    at F:\VS\instapack\node_modules\clean-css\lib\clean.js:105:29
    at Object.callback (F:\VS\instapack\node_modules\clean-css\lib\reader\read-sources.js:26:64)
    at doLoadOriginalSources (F:\VS\instapack\node_modules\clean-css\lib\reader\load-original-sources.js:67:22)
```

Fix: pin version 2.10.1

**Comment by ryanelian** [comment]
Removed from test matrices.
