### ISSUE TITLE
JS Build failes

### ISSUE THREAD

**Issue by stupkad** [ryanelian/instapack#879]
Hi there, 

I am new to instapack and just created a new project using ipack new empty.

When i run ipack, the js build failes. Any ideas?

[12:37:43] Production Mode: Build optimizations are enabled.
[12:37:43] Source Maps: Enabled (Hidden)
[12:37:45] Compiling index.scss in D:/Work/_Misc/ipack/client/css/
[12:37:45] Using TypeScript 3.9.6 (ESLint disabled)
[12:37:45] Type-checking start...
[12:37:45] ipack.css 96 B in D:/Work/_Misc/ipack/wwwroot/css/
[12:37:45] ipack.css.map 679 B in D:/Work/_Misc/ipack/wwwroot/css/
[12:37:45] Finished CSS build after 145 ms
[12:37:45] Compiling index.ts >> ES2015 in D:/Work/_Misc/ipack/client/js/
[12:37:45] TypeScript compilation finished! Minifying bundles...

FATAL ERROR during JS build:
HookWebpackError: compilation.getCache is not a function
    at makeWebpackError (C:\Users\dietm\AppData\Roaming\npm\node_modules\instapack\node_modules\webpack\lib\HookWebpackError.js:49:9)
    at C:\Users\dietm\AppData\Roaming\npm\node_modules\instapack\node_modules\webpack\lib\Compilation.js:1916:10
    at eval (eval at create (C:\Users\dietm\AppData\Roaming\npm\node_modules\instapack\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:26:1)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
-- inner error --
TypeError: compilation.getCache is not a function
    at new Cache (C:\Users\dietm\AppData\Roaming\npm\node_modules\instapack\node_modules\terser-webpack-plugin\dist\Webpack5Cache.js:15:30)
    at TerserPlugin.optimizeFn (C:\Users\dietm\AppData\Roaming\npm\node_modules\instapack\node_modules\terser-webpack-plugin\dist\index.js:529:21)
    at Hook.eval [as callAsync] (eval at create (C:\Users\dietm\AppData\Roaming\npm\node_modules\instapack\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:18:17)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\dietm\AppData\Roaming\npm\node_modules\instapack\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
    at cont (C:\Users\dietm\AppData\Roaming\npm\node_modules\instapack\node_modules\webpack\lib\Compilation.js:1913:32)
    at C:\Users\dietm\AppData\Roaming\npm\node_modules\instapack\node_modules\webpack\lib\Compilation.js:1956:8
    at C:\Users\dietm\AppData\Roaming\npm\node_modules\instapack\node_modules\neo-async\async.js:2830:7
    at Object.each (C:\Users\dietm\AppData\Roaming\npm\node_modules\instapack\node_modules\neo-async\async.js:2850:39)
    at Compilation.createChunkAssets (C:\Users\dietm\AppData\Roaming\npm\node_modules\instapack\node_modules\webpack\lib\Compilation.js:2693:12)
    at C:\Users\dietm\AppData\Roaming\npm\node_modules\instapack\node_modules\webpack\lib\Compilation.js:1951:12
    at eval (eval at create (C:\Users\dietm\AppData\Roaming\npm\node_modules\instapack\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at C:\Users\dietm\AppData\Roaming\npm\node_modules\instapack\node_modules\webpack\lib\optimize\ModuleConcatenationPlugin.js:460:32
    at processTicksAndRejections (internal/process/task_queues.js:76:11)

Types OK: Successfully checked TypeScript project without errors.
[12:37:45] Finished type-check after 700 ms

Regards,
Dietmar

**Comment by ryanelian** [comment]
Hi! I apologize for the inconvenience, may I know which version is that instapack version?

**Comment by stupkad** [comment]
Hi, npm installed 8.0.0-beta.14.

**Comment by stupkad** [comment]
Perhaps you have got an idea what could be wrong, I just tried the same on another machine. I love the idea of this project, because I never started using webpack becaue I did not invest that time to understand the configuration...

Anyway, thanks for your fast response!

**Comment by ryanelian** [comment]
I have confirmed that there is a regression due to sub-package (dependencies of a dependency) in version 8 beta 14.

However, the issue does not exist in the version 8 beta 12 and in the development branch. 

**Solution: please use version 8 Beta 12 until version 8 stable is released (very, VERY soon).**

*Example version 8 beta 12 test project:* 

```json
{
    "name": "myproject",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "devDependencies": {
        "instapack": "8.0.0-beta.12"
    },
    "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1",
        "new": "ipack new empty",
        "prod": "ipack",
        "dev": "ipack -dw"
    },
    "author": "",
    "license": "ISC"
}
```

### You should be able to create a new project by placing the above `package.json` in an empty folder and running these commands in sequence:

> npm install
> npm run new
> npm run prod

Thank you for using instapack and sorry for the inconveniences!
